### ISSUE TITLE
Clarify documentation with respect to transpiling a single source file

### ISSUE THREAD

**Issue by DaveJarvis** [kalai-transpiler/kalai#58]
I was looking to transpile a Rust program ([usvg](https://github.com/RazrFalcon/resvg/tree/master/usvg)) into Java. Here's what I tried (Java is installed in `/opt/jdk`):

``` bash
sudo su -
cd /tmp
curl -O https://download.clojure.org/install/linux-install-1.11.1.1200.sh
chmod +x ./linux-install-1.11.1.1200.sh
./linux-install-1.11.1.1200.sh -p /opt/clojure
wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
chmod +x lein
mv lein /opt/clojure/bin
```

Having those instructions (or similar) as part of an install section in the README may be helpful for others, including a note to add two lines near the top of `/opt/clojure/bin/lein`:

``` bash
JAVA_CMD=/opt/jdk/bin/java
LEIN_HOME=/opt/clojure
```

This could be streamlined using shell script (at the very least it would serve as a concise example of the software requirements):

``` bash
git clone https://github.com/echeran/kalai/main/scripts/install.sh
chmod +x install.sh
./install.sh --clojure=/opt/clojure --lein=/opt/clojure --kalai=/tmp/kalai
```

Continue as follows:

```
cd /tmp
git clone https://github.com/RazrFalcon/resvg/
git clone https://github.com/echeran/kalai/
cd kalai
export JAVA_HOME=/opt/jdk
make
clojure -M -m kalai.exec.main --verbose --src-dir=../resvg/src --transpile-dir=/tmp/resvg/java --languages java
```

**Expected**
Input Rust source files are transpiled and output to the `/tmp/resvg/java` directory as Java files.

**Actual**
It looks like the transpiler doesn't understand `//`, which strikes me as an error I've made in running the program:

```
Options {:src-dir "../resvg/src", :transpile-dir "/tmp/resvg/java", :languages "java", :verbose true}
transpiling source file: ../resvg/src/render.rs
Execution error (ExceptionInfo) at clojure.tools.reader.impl.errors/throw-ex (errors.clj:34).
file:/tmp/temp/kalai/../resvg/src/render.rs [line 1, col 3] Invalid symbol: //.

Full report at:
/tmp/clojure-15938165445097261021.edn
```

**Additional details**
Consider updating the documentation to show the _simplest_ usage imaginable: convert a single Rust source file into a single Java source file. I was anticipating I could do something like:

``` bash
mkdir -p /tmp/example/rust/ /tmp/example/java/

echo 'fn main() { println!("Hello World!"); }' > /tmp/example/rust/main.rs
clojure -M -m kalai.exec.main --verbose --src-dir=/tmp/example/rust --transpile-dir=/tmp/example/java 
```

However, even such a simple example didn't work:

```
Options {:src-dir "/tmp/example/rust", :transpile-dir "/tmp/example/java", :languages #{:kalai.emit.langs/rust :kalai.emit.langs/java}, :verbose true}
transpiling source file: /tmp/example/rust/main.rs
Syntax error compiling at (file:/tmp/example/rust/main.rs:1:1).
Can't take value of a macro: #'clojure.core/fn

Full report at:
/tmp/clojure-18058669059629100481.edn
```

Maybe I've misunderstood the intent of the program. I thought it was to transpile Java to Rust, Rust to Java, etc. Perhaps update the command-line options to make the usage clearer?

Possibly:

``` bash
clojure -M -m kalai.exec.main --help

Options:
  -i, --language-in   LANGUAGE   Source language (java, cpp, rust)
  -o, --language-out  LANGUAGE   Target language (java, cpp, rust)
  -s, --source-dir    DIRECTORY  src/  Input directory
  -t, --target-dir    DIRECTORY  out/  Output directory
  -x, --transpile-dir DIRECTORY  tra/  Intermediary transpilation directory
  -v, --verbose       Print progress
  -h, --help          Print usage information
```

**Comment by timothypratley** [comment]
Hi @DaveJarvis :wave:

Kalai only transpiles from Clojure to Rust and Java;
it cannot convert Rust into Java.

Thank you for the detailed steps and suggestions, I like your suggestions for clarifying the intent of the tool.

**Comment by echeran** [comment]
Thanks for the issue, you're justified in being confused from what you saw.  And +1 to all that Tim said.

Btw, your original intent to convert Rust code into Java code is interesting. It seemed unexpected to me because Rust and Java are designed for different and somewhat distinct use cases, imho. (I have some thoughts about this...) And I could imagine Rust->Java as easier than Java->Rust. In any case, if you want to discuss that more, feel free to [open a new discussion topic](https://github.com/echeran/kalai/discussions/). Thanks!
